# config.yaml

directory: '/Users/{USERNAME}/Downloads/test/'
check_frequency: 5 # in seconds
reporting_api: 'http://api.external.com/v1/report'
http_port: '9000'
socket_path: '/Users/{USERNAME}/.osquery/shell.em'
mongo_uri: 'mongodb://user:password@localhost:27017'
